package main

// @title          EVM Transaction Simulation API
// @version        1.0
// @description    Simulate any EVM transaction before sending  token deltas, gas, revert reasons, risk flags.
// @host           localhost:8081
// @BasePath       /
// @securityDefinitions.apikey ApiKeyAuth
// @in             header
// @name           X-API-Key

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joshdfg/evm-sim-api/config"
	httpController "github.com/joshdfg/evm-sim-api/internal/controller/http"
	"github.com/joshdfg/evm-sim-api/internal/repo"
	"github.com/joshdfg/evm-sim-api/internal/repo/evm"
	"github.com/joshdfg/evm-sim-api/internal/usecase"
	"github.com/joshdfg/evm-sim-api/pkg/logger"
	"github.com/redis/go-redis/v9"

	_ "github.com/joshdfg/evm-sim-api/docs" // swagger embed generated by `make swag`
)

func main() {
	// ── Config ────────────────────────────────────────────────────────────────
	cfg, err := config.New()
	must(err, "load config")

	// ── Logger ────────────────────────────────────────────────────────────────
	// Signature: New(level, appName, version, env)
	log := logger.New(cfg.Log.Level, cfg.App.Name, cfg.App.Version, cfg.App.Env)

	// Startup summary every resolved value printed once.
	// If any field looks wrong here, fix it in .env before going further.
	log.Info().
		Str("service", cfg.App.Name).
		Str("build", cfg.App.Version).
		Str("log_level", cfg.Log.Level).
		Str("http_port", cfg.HTTP.Port).
		Str("pg_host", cfg.Postgres.Host).
		Str("redis_addr", cfg.Redis.Addr()).
		Str("archive_node", maskURL(cfg.EVM.ArchiveNodeURL)).
		Msg("config loaded  if any field looks wrong, check .env against .env.example")

	// ── Postgres ──────────────────────────────────────────────────────────────
	pool, err := pgxpool.New(context.Background(), cfg.Postgres.DSN())
	must(err, "connect postgres")
	defer pool.Close()

	if err := pool.Ping(context.Background()); err != nil {
		must(err, "ping postgres")
	}
	log.Info().Str("host", cfg.Postgres.Host).Msg("postgres connected")

	// ── Redis ─────────────────────────────────────────────────────────────────
	rdb := redis.NewClient(&redis.Options{
		Addr:     cfg.Redis.Addr(),
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		must(err, "ping redis")
	}
	defer rdb.Close()
	log.Info().Str("addr", cfg.Redis.Addr()).Msg("redis connected")

	// ── EVM archive fork (innermost layer) ───────────────────────────────────
	archiveFork, err := evm.NewArchiveNodeFork(
		cfg.EVM.ArchiveNodeURL,
		cfg.EVM.SimulationTimeoutSeconds,
		cfg.EVM.MaxGasLimit,
		log,
	)
	must(err, "connect archive node")
	log.Info().Msg("archive node connected")

	// ── Decorator chain: archive → cache → logging ────────────────────────────
	// Add a MetricsFork wrapper here for Prometheus without touching anything else.
	cachedFork := repo.NewSimulationCacheRepo(
		archiveFork,
		rdb,
		cfg.EVM.CacheTTLSeconds,
		cfg.EVM.PendingCacheTTLSeconds,
		log,
	)
	loggedFork := repo.NewSimulationLoggingRepo(cachedFork, log)

	// ── Supporting components ─────────────────────────────────────────────────
	// tokenDecoder shares the same ethclient no second dial.
	tokenDecoder := evm.NewEVMTokenDecoder(archiveFork.Client(), log)
	riskAnalyzer := usecase.NewRiskAnalyzer()

	// ── Repos ─────────────────────────────────────────────────────────────────
	simRepo := repo.NewSimulationPostgresRepo(pool)
	apiKeyRepo := repo.NewAPIKeyPostgresRepo(pool)

	// ── Use cases ─────────────────────────────────────────────────────────────
	simUC := usecase.NewSimulationUseCase(loggedFork, simRepo, tokenDecoder, riskAnalyzer)

	// ── HTTP server ───────────────────────────────────────────────────────────
	router := httpController.NewRouter(simUC, apiKeyRepo, log)

	srv := &http.Server{
		Addr:         ":" + cfg.HTTP.Port,
		Handler:      router,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: time.Duration(cfg.EVM.SimulationTimeoutSeconds+10) * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		log.Info().Str("port", cfg.HTTP.Port).Msg("http server listening")
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatal().Err(err).Msg("http server error")
		}
	}()

	// ── Graceful shutdown ─────────────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Info().Msg("shutdown signal received draining connections")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		if err := srv.Shutdown(ctx); err != nil {
			log.Error().Err(err).Msg("graceful shutdown failed")
		}
		log.Info().Msg("server stopped cleanly")
		log.Error().Err(err).Msg("graceful shutdown failed")
	}
	log.Info().Msg("server stopped cleanly")
}

// must terminates the process on startup errors only.
func must(err error, msg string) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: %s: %v\n", msg, err)
		os.Exit(1)
	}
}

// maskURL hides the API key portion of an archive node URL for safe logging.
// "https://eth-mainnet.g.alchemy.com/v2/abc123" → "https://eth-mainnet.g.alchemy.com/***"
func maskURL(rawURL string) string {
	if len(rawURL) < 10 {
		return "***"
	}
	for i := 8; i < len(rawURL); i++ {
		if rawURL[i] == '/' {
			return rawURL[:i] + "/***"
		}
	}
	return rawURL[:12] + "***"
}
