package http

import (
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/rs/zerolog"
	"github.com/joshdfg/evm-sim-api/internal/usecase"
)

// NewRouter wires all routes, middleware, and handlers into a *gin.Engine.
// Called once from main.go — this is the only place that knows about all handlers.
func NewRouter(
	simUC *usecase.SimulationUseCase,
	apiKeyRepo usecase.APIKeyRepository,
	log zerolog.Logger,
) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)

	r := gin.New() // bare engine — no default logger/recovery; we supply our own

	// ── Global middleware ─────────────────────────────────────────────────────
	r.Use(Recovery(log))
	r.Use(RequestLogger(log))
	r.Use(CORS())
	r.Use(RateLimiter("300-M")) // 300 requests / minute per IP (outer guard)

	// ── Public routes ─────────────────────────────────────────────────────────
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Swagger UI — generated by `make swag`. Disable in production if desired.
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ── Authenticated API routes ──────────────────────────────────────────────
	v1 := r.Group("/v1")
	v1.Use(APIKeyAuth(apiKeyRepo))

	simHandler := NewSimulationHandler(simUC)
	v1.POST("/simulate", simHandler.Simulate)
	v1.GET("/simulations/:id", simHandler.GetSimulation)

	return r
}
