// Package docs is auto-generated by swaggo/swag.
// Run `make swag` to regenerate after changing handler annotations.
// This stub file allows the project to compile before the first `swag init`.
package docs
